import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html = fs.readFileSync(new URL('../docs/assets/dashboard-demo.html', import.meta.url), 'utf8');
const source = html.match(/<script>([\s\S]+)<\/script>/)[1];
const elements = new Map();
const document = {
  getElementById(id) {
    if (!elements.has(id)) elements.set(id, { textContent: '', innerHTML: '' });
    return elements.get(id);
  }
};
vm.runInNewContext(source, { document });
const get = id => elements.get(id);
assert.match(get('count').textContent, /2 accepted · 4 remaining/);
const activePlot = get('plot').innerHTML;
get('future').onclick();
assert.notEqual(get('plot').innerHTML, activePlot, 'active task range advances with the observation clock');
get('done').onclick();
const completed = { plot: get('plot').innerHTML, clock: get('clock').textContent };
const freshness = get('freshness').textContent;
get('future').onclick();
assert.equal(get('plot').innerHTML, completed.plot, 'completed chart range is frozen');
assert.equal(get('clock').textContent, completed.clock, 'completed duration is frozen');
assert.notEqual(get('freshness').textContent, freshness, 'observation freshness advances separately');
assert.match(get('count').textContent, /6 accepted · 0 remaining/);
console.log('Dashboard state checks passed: active clock, completed clock, count and freshness separation.');

// Exercise the downloadable renderer against decisions, unsafe text, stale data,
// completion and a failed fetch. These are contracts of the working dashboard.
const liveHTML=fs.readFileSync(new URL('../templates/dashboard.html',import.meta.url),'utf8');
const liveSource=liveHTML.match(/<script>([\s\S]+)<\/script>/)[1];
const sample=JSON.parse(fs.readFileSync(new URL('../templates/workflow-state.example.json',import.meta.url),'utf8'));
const nodes=new Map();
const state=structuredClone(sample);
let failed=false;
const context=vm.createContext({document:{getElementById(id){if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',className:''});return nodes.get(id);}},URL,Date,fetch:async()=>{if(failed)throw Error('offline');return {ok:true,json:async()=>state};},setInterval:()=>0});
vm.runInContext(liveSource,context);
await vm.runInContext('refresh()',context);
assert.match(nodes.get('approval-count').textContent,/1 pending/);
assert.match(nodes.get('decisions').innerHTML,/Suggested resolution:/);
assert.match(nodes.get('next').textContent,/Next action: Coordinator/);
assert.match(nodes.get('health').textContent,/source/);
state.updated_at='2000-01-01T00:00:00Z';
await vm.runInContext('refresh()',context);
assert.match(nodes.get('health').textContent,/STALE source/);
assert.equal(nodes.get('health').className,'error');
state.updated_at=sample.updated_at;
state.decisions[0].status='approved';state.decisions[0].answer='Approved';state.decisions[0].answered_at='2030-01-01T10:33:00Z';
state.current_stage='<img src=x onerror=alert(1)>';
state.evidence=['<script>unsafe</script>'];
await vm.runInContext('refresh()',context);
assert.equal(nodes.get('approval-count').textContent,'No approvals pending');
assert.equal(nodes.get('decisions').innerHTML,'');
assert.match(nodes.get('answered').innerHTML,/Approved/);
assert.match(nodes.get('evidence').innerHTML,/&lt;script&gt;/);
assert.equal(vm.runInContext('safeLink("javascript:alert(1)","Blocked")',context),'Blocked');
assert.match(liveHTML, /viewBox="0 0 980 360"/);
assert.match(liveHTML, /aspect-ratio:980\/360/);
state.tasks.forEach((t,i)=>{t.status='accepted';t.accepted_at='2030-01-01T11:00:00Z';});
state.completed_at='2030-01-01T11:00:00Z';state.history.push({at:state.completed_at,remaining:0,label:'Final gate accepted'});
context.sample=state;
vm.runInContext('render(sample,Date.parse("2030-01-01T12:00:00Z"))',context);
const frozen=nodes.get('plot').innerHTML;
vm.runInContext('render(sample,Date.parse("2031-01-01T12:00:00Z"))',context);
assert.equal(nodes.get('plot').innerHTML,frozen);
assert.match(nodes.get('count').textContent,/0 remaining/);
await vm.runInContext('refresh()',context);
failed=true;
await vm.runInContext('refresh()',context);
assert.match(nodes.get('health').textContent,/retaining last good state/);
assert.equal(nodes.get('health').className,'error');
assert.match(nodes.get('count').textContent,/0 remaining/);
state.completed_at=null;state.tasks[0].status='pending';state.decisions[0].status='pending';
state.history=[];
vm.runInContext('render(sample,Date.parse("2030-01-01T10:00:00Z"))',context);
assert.match(nodes.get('plot').innerHTML,/No recorded gate history/);
assert.throws(()=>vm.runInContext('validate({...sample,completed_at:"2030-01-01T11:00:00Z"})',context),/all accepted gates/);
assert.throws(()=>vm.runInContext('validate({...sample,updated_at:"invalid"})',context),/timestamp/);
console.log('Live dashboard checks passed: decisions, safe text/links, bounded SVG, final clock, empty history and failed refresh.');
